name: tmdb_easy
description: easytmdb is a data fetching library based on THE MOVIE DATABASE(TMDB) server.
version: 1.3.0
homepage: https://github.com/khalid3011/easy_tmdb

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
